# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/xraph/steel/discussions
    about: Ask questions and discuss ideas with the community

  - name: 🔒 Security Issue
    url: https://github.com/xraph/steel/security/advisories/new
    about: Report a security vulnerability (private)

  - name: 📚 Documentation
    url: https://github.com/xraph/steel/wiki
    about: Read the documentation and guides
