name: Documentation Issue
description: Report an issue with documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - API Documentation
        - README
        - Code Comments
        - Examples
        - Tutorials
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documentation located? (URL, file path, etc.)

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please describe it.
